/* Legale+ , catalogos de dominio do Legale (cache/fallback).
 * Fonte: mapeamento real do Legale Web (projeto Wrapper Legale), 2026-07-14.
 * Uso ADITIVO: os modulos continuam lendo do proprio Legale; estes catalogos
 * servem de fallback quando a leitura ao vivo falha e para acelerar seletores.
 * Nao substitui nada; se estiver desatualizado, a leitura ao vivo prevalece. */
window.LegalePlus = window.LegalePlus || {};
(function (LP) {
  LP.catalogos = {
    atualizadoEm: '2026-07-14',
    unidades: [{"id": "1", "nome": "DBZ"}, {"id": "4", "nome": "GZN"}],
    tipoCobranca: [{"id": "S", "nome": "Cobrável"}, {"id": "N", "nome": "Não cobrável"}],
    areas: [{"id": "18", "nome": "ADMINISTRAÇÃO"}, {"id": "7", "nome": "ADMINISTRATIVO"}, {"id": "5", "nome": "AMBIENTAL"}, {"id": "30", "nome": "BUSINESS - DR ANDRE"}, {"id": "27", "nome": "BUSINESS - DR ISADORA"}, {"id": "28", "nome": "BUSINESS - DRA LARISSA"}, {"id": "29", "nome": "BUSINESS - RUAN"}, {"id": "1", "nome": "CÍVEL"}, {"id": "15", "nome": "COMERCIAL"}, {"id": "21", "nome": "CONSULTIVO"}, {"id": "17", "nome": "CONSUMIDOR"}, {"id": "20", "nome": "CRIMINAL"}, {"id": "11", "nome": "INTERNACIONAL"}, {"id": "19", "nome": "INTERNACIONAL CÍVEL"}, {"id": "12", "nome": "INTERNACIONAL TRIBUTÁRIA"}, {"id": "23", "nome": "OFFICE - DR GUILHERME"}, {"id": "22", "nome": "OFFICE - DR THIAGO"}, {"id": "24", "nome": "OFFICE - DR. EDUARDO"}, {"id": "26", "nome": "OFFICE - DRA LAYSA"}, {"id": "25", "nome": "OFFICE - DRA. GABRIELA"}, {"id": "3", "nome": "PENAL"}, {"id": "14", "nome": "PENAL AMBIENTAL"}, {"id": "13", "nome": "PENAL TRIBUTÁRIA"}, {"id": "16", "nome": "SOCIATÁRIO"}, {"id": "4", "nome": "TRABALHISTA"}, {"id": "6", "nome": "TRÂNSITO"}, {"id": "9", "nome": "TRIBUTÁRIA ESTADUAL"}, {"id": "8", "nome": "TRIBUTÁRIA FEDERAL"}, {"id": "10", "nome": "TRIBUTÁRIA MUNICIPAL"}],
    tipos: [{"id": "PT", "nome": "AÇÃO NOVA"}, {"id": "6", "nome": "ACOMPANHAMENTO"}, {"id": "57", "nome": "ADMINISTRATIVO"}, {"id": "59", "nome": "ALINHAMENTO"}, {"id": "7", "nome": "ALTERAR CADASTRO"}, {"id": "33", "nome": "ANÁLISE DE PUBLICAÇÕES"}, {"id": "34", "nome": "ANÁLISE DOCUMENTAL"}, {"id": "37", "nome": "ANÁLISE PROCESSUAL"}, {"id": "27", "nome": "ATA DE REUNIÃO"}, {"id": "AU", "nome": "AUDIÊNCIA"}, {"id": "62", "nome": "BRANDING"}, {"id": "45", "nome": "COBRANÇA"}, {"id": "28", "nome": "COBRANÇA DE HONORÁRIOS"}, {"id": "43", "nome": "COBRANÇA EXTRAJUDICIAL"}, {"id": "1", "nome": "COBRAR ATA/PROTOCOLO"}, {"id": "RC", "nome": "COBRAR PROTOCOLO FATAL"}, {"id": "64", "nome": "COMERCIAL"}, {"id": "31", "nome": "CONFECÇÃO DE DOCUMENTOS"}, {"id": "46", "nome": "CONFERÊNCIA"}, {"id": "16", "nome": "CONSULTORIA EQUIPE"}, {"id": "26", "nome": "CONSULTORIA JURÍDICA"}, {"id": "52", "nome": "CONTATO COM CLIENTE"}, {"id": "30", "nome": "CONTRATO"}, {"id": "25", "nome": "CONTRATO DE HONORÁRIOS"}, {"id": "19", "nome": "CRIAÇÃO DE CONTEÚDO"}, {"id": "63", "nome": "CULTURA"}, {"id": "49", "nome": "DESENVOLVIMENTO INTERNO"}, {"id": "4", "nome": "DILIGÊNCIA"}, {"id": "50", "nome": "DUE DILIGENCE"}, {"id": "17", "nome": "EDIÇÃO DE VÍDEO"}, {"id": "47", "nome": "EMISSÃO DE NOTAS FISCAIS/BOLETOS"}, {"id": "32", "nome": "ESTUDO TÉCNICO INTERNO"}, {"id": "48", "nome": "EVENTOS E PROJETOS INSTITUCIONAIS"}, {"id": "18", "nome": "GRAVAÇÃO DE VÍDEO/PODCAST"}, {"id": "9", "nome": "INFORMAÇÃO FINANCEIRA"}, {"id": "41", "nome": "INFORMATIVOS"}, {"id": "OU", "nome": "JULGAMENTO"}, {"id": "54", "nome": "LEVANTAMENTO DE INFORMAÇÕES"}, {"id": "15", "nome": "NEGOCIAÇÃO"}, {"id": "39", "nome": "NOTIFICAÇÃO EXTRAJUDICIAL"}, {"id": "65", "nome": "NUCLEO DE ESTRATÉGIA"}, {"id": "60", "nome": "OPERACIONAL"}, {"id": "53", "nome": "ORGANIZAÇÃO"}, {"id": "55", "nome": "OUTROS"}, {"id": "51", "nome": "PAGAMENTOS"}, {"id": "38", "nome": "PERÍCIA"}, {"id": "PE", "nome": "PESSOAL"}, {"id": "44", "nome": "PLANEJAMENTO"}, {"id": "61", "nome": "PLANEJAMENTO ESTRATÉGICO"}, {"id": "20", "nome": "POSTAGEM REDE SOCIAL"}, {"id": "3", "nome": "PRAZO"}, {"id": "36", "nome": "PRAZO DE PREPARAÇÃO"}, {"id": "PZ", "nome": "PRAZO FATAL"}, {"id": "5", "nome": "PRAZO INTERNO"}, {"id": "35", "nome": "PREENCHIMENTO DE PLANILHAS/RELATÓRIOS"}, {"id": "58", "nome": "PRODUÇÃO"}, {"id": "24", "nome": "PROPOSTA DE HONORÁRIOS"}, {"id": "29", "nome": "PROSPECÇÃO"}, {"id": "22", "nome": "PUBLICAÇÃO"}, {"id": "10", "nome": "RELATÓRIOS"}, {"id": "12", "nome": "REUNIÃO COM CLIENTE"}, {"id": "13", "nome": "REUNIÃO COM FORNECEDOR"}, {"id": "14", "nome": "REUNIÃO DE ATENDIMENTO INICIAL"}, {"id": "42", "nome": "REUNIÃO DIVERSA"}, {"id": "11", "nome": "REUNIÃO INTERNA"}, {"id": "8", "nome": "REVISÃO"}, {"id": "23", "nome": "SUCUMBÊNCIA"}, {"id": "21", "nome": "TIME SHEET"}, {"id": "40", "nome": "TREINAMENTO"}],
    usuarios: [{"id": "4", "nome": "ANDRE.MELO"}, {"id": "6", "nome": "EDUARDO.MARTINS"}, {"id": "7", "nome": "FABIO.DELBIANCO"}, {"id": "8", "nome": "FABIO.GIBELI"}, {"id": "9", "nome": "FELIPE.BENEDETTI"}, {"id": "13", "nome": "FRANCIELLY.CAETANO"}, {"id": "10", "nome": "GABRIELA.REZENDE"}, {"id": "11", "nome": "GUILHERME.ZOCOLLARO"}, {"id": "3", "nome": "ISADORA.SOARES"}, {"id": "12", "nome": "JOSE.MELO"}, {"id": "5", "nome": "LARISSA.VIEIRA"}, {"id": "14", "nome": "LAYSA.FREITAS"}, {"id": "15", "nome": "LUIS.MARQUES"}, {"id": "23", "nome": "MARIA.FERNANDA"}, {"id": "16", "nome": "MARIA.NATALI"}, {"id": "17", "nome": "MARINA.COLAFEMEA"}, {"id": "24", "nome": "NICOLAS.SANTOS"}, {"id": "19", "nome": "PATRICIA"}, {"id": "1", "nome": "QUALY"}, {"id": "18", "nome": "RUAN.FERREIRA"}, {"id": "20", "nome": "THAIS.FLAUSINO"}, {"id": "21", "nome": "THIAGO.BRENTINI"}, {"id": "22", "nome": "VINICIUS.MONTSERRAT"}],
    // helper: tipos no formato {id,label} usado pelo seletor de atividade.
    tiposComoOpcoes() { return (this.tipos||[]).map(function(t){return {id:t.id,label:t.nome};}); },
  };
})(window.LegalePlus);
